// Generated by CoffeeScript 1.4.0

/*
The MIT License

Copyright (c) 2013-2014 Wilfred Springer, http://nxt.flotsam.nl/

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/


  'use-strict';
  angular.module('pouchdb', ['ng'])

    .provider('pouchdb', function() {
        return {
          withAllDbsEnabled: function() {
            return PouchDB.enableAllDbs = true;
          },
          $get: function($q, $rootScope, $timeout) {
            var qify;
            qify = function(fn) {
              return function() {
                var args, callback, deferred;
                deferred = $q.defer();
                callback = function(err, res) {
                  return $timeout(function() {
                    if (err) {
                      return deferred.reject(err);
                    } else {
                      return deferred.resolve(res);
                    }
                  });
                };
                args = arguments != null ? Array.prototype.slice.call(arguments) : [];
                args.push(callback);
                fn.apply(this, args);
                return deferred.promise;
              };
            };
            return {
              create: function(name, options) {
                var db;
                db = new PouchDB(name, options);
                return {
                  id: db.id,
                  put: qify(db.put.bind(db)),
                  post: qify(db.post.bind(db)),
                  get: qify(db.get.bind(db)),
                  remove: qify(db.remove.bind(db)),
                  bulkDocs: qify(db.bulkDocs.bind(db)),
                  allDocs: qify(db.allDocs.bind(db)),
                  changes: function(options) {
                    var clone;
                    clone = angular.copy(options);
                    clone.onChange = function(change) {
                      return $rootScope.$apply(function() {
                        return options.onChange(change);
                      });
                    };
                    return db.changes(clone);
                  },
                  putAttachment: qify(db.putAttachment.bind(db)),
                  getAttachment: qify(db.getAttachment.bind(db)),
                  removeAttachment: qify(db.removeAttachment.bind(db)),
                  query: qify(db.query.bind(db)),
                  info: qify(db.info.bind(db)),
                  compact: qify(db.compact.bind(db)),
                  revsDiff: qify(db.revsDiff.bind(db)),
                  replicate: {
                    to: db.replicate.to.bind(db),
                    from: db.replicate.from.bind(db),
                    sync: db.replicate.sync.bind(db)
                  },
                  destroy: qify(db.destroy.bind(db)),

                  // Wrap Plugin Methods
                  // https://github.com/nolanlawson/pouchdb-authentication
                  signup: qify(db.signup.bind(db)),
                  login: qify(db.login.bind(db)),
                  logout: qify(db.logout.bind(db)),
                  getSession: qify(db.getSession.bind(db)),
                  getUser: qify(db.getUser.bind(db)),

                  // My Hacks
                  onChange: function(f) {
                      f();
                      db.info(function(err, info) {
                          db.changes({
                              since: info.update_seq,
                              live: true
                          }).on('change', function() {
                              f();
                          })
                      });
                  }

              };
              }
            };
          }
        };
      });







